import { ReactNode } from "react";
import ReactMarkdown from "react-markdown";
import { Copy, Loader2, Sparkles, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

interface AIToolShellProps {
  title: string;
  description: string;
  icon: ReactNode;
  inputLabel: string;
  inputPlaceholder: string;
  cta: string;
  input: string;
  setInput: (v: string) => void;
  output: string;
  setOutput: (v: string) => void;
  loading: boolean;
  onRun: () => void;
  extra?: ReactNode;
}

export function AIToolShell(props: AIToolShellProps) {
  const {
    title, description, icon, inputLabel, inputPlaceholder, cta,
    input, setInput, output, setOutput, loading, onRun, extra,
  } = props;

  const copy = () => {
    navigator.clipboard.writeText(output);
    toast.success("Copied to clipboard");
  };

  return (
    <div className="mx-auto flex w-full max-w-6xl flex-col gap-6 p-6 md:p-8">
      <header className="flex items-start gap-4">
        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-gradient-primary shadow-glow">
          {icon}
        </div>
        <div>
          <h1 className="text-2xl font-semibold md:text-3xl">{title}</h1>
          <p className="mt-1 max-w-2xl text-sm text-muted-foreground">{description}</p>
        </div>
      </header>

      <div className="grid gap-6 lg:grid-cols-2">
        <section className="flex flex-col gap-3 rounded-xl border bg-card p-5 shadow-soft">
          <div className="flex items-center justify-between">
            <label className="text-sm font-medium">{inputLabel}</label>
          </div>
          <Textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={inputPlaceholder}
            className="min-h-[280px] resize-y bg-background"
          />
          {extra}
          <Button
            onClick={onRun}
            disabled={loading || !input.trim()}
            className="bg-gradient-primary text-primary-foreground shadow-glow hover:opacity-90"
          >
            {loading ? (
              <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Generating…</>
            ) : (
              <><Sparkles className="mr-2 h-4 w-4" /> {cta}</>
            )}
          </Button>
        </section>

        <section className="flex flex-col gap-3 rounded-xl border bg-card p-5 shadow-soft">
          <div className="flex items-center justify-between">
            <label className="text-sm font-medium">AI Output (editable)</label>
            <Button variant="ghost" size="sm" onClick={copy} disabled={!output}>
              <Copy className="mr-1 h-3.5 w-3.5" /> Copy
            </Button>
          </div>
          <Textarea
            value={output}
            onChange={(e) => setOutput(e.target.value)}
            placeholder="Your AI-generated result will appear here. You can edit it freely."
            className="min-h-[280px] resize-y bg-background font-mono text-sm"
          />
          {output && (
            <div className="rounded-lg border bg-muted/40 p-4">
              <p className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">
                Preview
              </p>
              <div className="prose prose-sm max-w-none dark:prose-invert">
                <ReactMarkdown>{output}</ReactMarkdown>
              </div>
            </div>
          )}
        </section>
      </div>

      <div className="flex items-start gap-2 rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-900 dark:text-amber-200">
        <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
        <p>
          <strong>Responsible AI:</strong> Outputs are generated by an AI model and may contain
          inaccuracies, omissions, or bias. Always review and edit before sending, sharing, or
          acting on them. Do not paste confidential information you wouldn't share with a third party.
        </p>
      </div>
    </div>
  );
}
